version: "2"
plugins:
  duplication:
    enabled: false
  structure:
    enabled: false
  cppcheck:
    check: all
    enabled: true
    config:
      language: c
      max_configs: force
      stds:
        - c11
